### ISSUE TITLE
Named parameters are not required by default in signatures

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#252]
## Context
Named parameters are not required.

## Issue

Named parameters by default are required unless given an optional value, according to [Function::Parameters](https://metacpan.org/pod/Function::Parameters#Named-parameters). However, I don't see this:

```
package App::User;

use Do 'Class';

has 'fname';
has 'lname';

method greet(:$name) {
  my $fname = $self->fname;
  my $lname = $self->lname;

  "Hey $name, I'm $fname $lname";
}

package main;

my $user = App::User->new(fname => 'Al', lname => 'Newkirk');

# no name provided
say $user->greet();

1;
```

Running that prints:

```
Use of uninitialized value $name in concatenation (.) or string at greet.pl line 13.
Hey , I'm Al Newkirk
```

However, if I use `Function::Parameters` directly:

```
package App::User;

use Do 'Class';
use Function::Parameters;

has 'fname';
has 'lname';

method greet(:$name) {
  my $fname = $self->fname;
  my $lname = $self->lname;

  "Hey $name, I'm $fname $lname";
}

package main;

my $user = App::User->new(fname => 'Al', lname => 'Newkirk');

# no name provided
say $user->greet();

1;
```

Then I get the correct error:

```
Too few arguments for method greet (expected 3, got 1) at greet.pl line 20.
```

**Comment by iamalnewkirk** [comment]
@srchulo This is by design, for backward-compatibility, because this framework has been using Function::Parameters since before its refactor where it started enforcing this by default.

This framework turns this off using https://metacpan.org/pod/Function::Parameters#check_argument_count.

That having been said, version 2.00 of this project is planning to break with backward-compatibility so maybe we can enable it then!

**Comment by srchulo** [comment]
@iamalnewkirk Thanks for the explanation!

**Comment by iamalnewkirk** [comment]
This project has been deprecated in favor of https://metacpan.org/release/Data-Object and other separate releases!
