### ISSUE TITLE
snakecase isn't parallel to camelcase

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#253]
In [Data::Object::String](https://metacpan.org/pod/Data::Object::String), [camelcase](https://metacpan.org/pod/Data::Object::String#camelcase) joins words by capitalizing them to make make them camel case. The parallel [snakecase](https://metacpan.org/pod/Data::Object::String#snakecase), however, doesn't really create snakecase, because it just joins all of the words instead of putting underscores between the words to make real [Snake case](https://en.wikipedia.org/wiki/Snake_case).

**Comment by iamalnewkirk** [comment]
👍 Thanks for finding this! Somehow `snakecase` is returning `pascalcase` unintentionally.

**Comment by srchulo** [comment]
@jjatria Thanks for that link. That's a good find, as kebab_case is actually what I wanted. I wonder if it would make sense to add some more of these to `Data::Obejct::String`?

**Comment by jjatria** [comment]
@iamalnewkirk Would a PR that implemented this using String::CamelSnakeKebab be acceptable? It looks like that module only depends on Sub::Exporter, and that is already in Data::Object's dependency tree.
It would mean we don't have to _think_ about how to resolve the casing rules for the more obscure corner cases, and that implementing some of the other casing rules would also be trivial (like kebab-case).

**Comment by jjatria** [comment]
@iamalnewkirk While looking at the tests I came across this description of the (mistaken) expected behaviour of `snakecase`:

> The snakecase method modifies the string such that it will no longer have any
non-alphanumeric characters and each word (group of alphanumeric characters
separated by 1 or more non-alphanumeric characters) is capitalized. The only
difference between this method and the camelcase method is that this method
ensures that the first character will always be lowercased. Note, this method
modifies the string. This method returns a string value.

Changing the word joining rules is trivial, but the part about it removing non-alphanumeric characters seems unexpected to me. Just to clarify: what would you expect the outcome of calling `snakecase` on the strings below to be?

For reference, I give the output of String::CamelSnakeKebab's `lower_snake_case` (which in hindsight makes some odd choices, like returning an empty string when it gives up; in these cases, I'd expect the same string to be returned).

| Input             | Output (from `lower_snake_case`) |
| ------------------| ---------------------------------|
| `"hello world"`   | `"hello_world"`                  |
| `"hello  world"`  | `"hello_world"`                  |
| `"helloWorld"`    | `"hello_world"`                  | 
| `"hello-world"`   | `"hello_world"`                  |
| `"helloworld"`    | `"helloworld"`                   |
| `"Hello, World!"` | `"hello_,_world_!"`              |
| `"__"`            | `""`                             |
| `""`              | `""`                             |

(The "input" in the second row should have two consecutive spaces, but it seems Github is trying to be smart and removes it).

**Comment by iamalnewkirk** [comment]
@jjatria @srchulo I would love PRs! Please take a look at the CONTRIBUTING.mkdn doc for an overview about documentation and testing. I'll flush it out more in a few hours.

@jjatria I'm a little torn on what to do here. I want to keep Data::Object lean in terms of dependencies but I also don't want to reinvent the wheel. I really don't want to pull in another department, esp. string::CamelSnakeKebab.

Although I've never thought of it as a plug-in system, the data objects use autoloading and functors as methods, so technically someone could publish a new distribution named Data::Object::String::Func::Case and the string object will dispatch to it. E.g. $string->case('kebab')

**Comment by srchulo** [comment]
@iamalnewkirk noted! I will take a look at the CONTRIBUTING.mkdn doc :)

**Comment by iamalnewkirk** [comment]
@jjatria This is interesting, I just noticed that String::CamelSnakeKebab lower_snake_case  transforms "helloWorld" to "hello_world". That's super strange to me. I would expect "helloworld".

**Comment by jjatria** [comment]
@iamalnewkirk Yeah, I think this is because String::CamelSnakeKebab tries to make all of its transformations play nicely with each other. So it first breaks down words with all of the rules it knows about (in which case `"helloWorld"` is interpreted to be "hello" and "world" joined using camel case) and then it joins them with whatever method you wanted. 

Not saying this is the best decision, just what I think is the rationale behind this choice. :)
