### ISSUE TITLE
'Data::Object::String'  did not pass type constraint "Str"

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#254]
[Data::Object::String](https://metacpan.org/pod/Data::Object::String) doesn't match the `Str` constraint, which causes issues when `Data::Object` returns a `Data::Object::String`:

```
use Do;

my %h = (
    a => 'b',
    c => 'd',
    e => 'f',
);

%h->keys->each_value( fun ($value) {
    say %h->get($value);
});
```

```
Data::Object::Array::each_value(arg1, arg2, @args): Data::Object::Hash::get(arg1, arg2): Reference bless( do{\(my $o = "c")}, 'Data::Object::String' ) did not pass type constraint "Str" in /home/user/perl5/perlbrew/perls/perl-5.30.0/lib/site_perl/5.30.0/Data/Object/Role/Functable.pm at line 38
        Data::Object::Role::Functable::catch {...}  in /home/user/perl5/perlbrew/perls/perl-5.30.0/lib/site_perl/5.30.0/Try/Tiny.pm at line 123
        Try::Tiny::try in /home/user/perl5/perlbrew/perls/perl-5.30.0/lib/site_perl/5.30.0/Data/Object/Role/Functable.pm at line 39
        Data::Object::Role::Functable::__ANON__ in test.pl at line 13
        main::main in test.pl at line 19
```

**Comment by jjatria** [comment]
What would you expect your snippet to print? If I'm reading it right, it gets the keys (`[ 'a', 'c', 'e' ]`) and then calls `each_value` on that, but that doesn't sound right (because surely `each_value` makes sense when we have pairs, but this array does not even have an even number of elements).

Are you sure you don't mean the following?

``` perl
%h->each_key( fun ($value) {
    say %h->get($value);
});
```

That prints the values without a warning on my machine.

**Comment by iamalnewkirk** [comment]
@srchulo Yes, you're correct. This is intentional, however, your stumbling upon it makes me wonder whether this behavior should change.

I.e. In "Do", a `Str` is different from a `StrObject`. This is intentional given that we want to differentiate between them and allow developers to specify (via constraint) which type of value they expect. Quoting the string object will cause it to become a string again, so your snippet would work if you wrote:

```perl
%h->keys->each_value( fun ($value) {
    say %h->get("$value");
});
```

I acknowledge that it's confusing if you don't know the framework. I'm not sure if it should be changed. What do you think?

**Comment by iamalnewkirk** [comment]
@jjatria You right, that call gets the keys as an `ArrayObject` and then calls `each_value`. An array has values, and we refer to its indices as keys as a convention, i.e. to make it easy to use and guess what methods are available if you've used a `HashObject`.

**Comment by srchulo** [comment]
@jjatria so as @iamalnewkirk mentioned, I used keys to get  the `ArrayObject`, and then I used `each_value` because `each` provides `$index` and `$value` to the subroutine, and I only wanted `$value`.

@iamalnewkirk I understand the distinction, but I think it requires you to think a lot about what you're doing/want, and in the end makes using `Do` less natural. For instance, I have to realize that `$value` is a `StrObject`, which means I need to interpolate it as a string for it to actually work:

```
say %h->get("$value");
```

I think this is particularly confusing, because:

```
say $h{$value};
```

Works, since `StrObject` overloads `""`. I think one would expect `%h->get($value)` to be parallel to `$h{$value}`.

Would it make sense for the `Data::Object`s to provide coercions into their unboxed types?

**Comment by iamalnewkirk** [comment]
Just added a necessary piece for resolving this issue distro-wide, see #272. I'm going to start working on this shortly. Essentially, all function class attribute constraints will use their `{Thing}Like` variants, e.g. `isa => 'String'` will become `isa => 'StringLike`.
