### ISSUE TITLE
Towards Modularity

### ISSUE THREAD

**Issue by iamalnewkirk** [iamalnewkirk/do#324]
Since we are just a few features and commits away from a version 2.00 release, which I intend to signify API stability, I'm looking for feedback on the following major change proposals:

## More Modularity

Currently, the Do framework enhances Moo, adds method/function signatures, and provides a  pluggable standard library. Changing any of those underlying mechanisms requires a full framework release which could cause some to question it's stability. I'm proposing separating the pluggable standard library from the "core", e.g.

- Do: Framework
- Dox: Pluggable Standard Library

I'm not sure about the name but it's the one I hate the least. Dox will depend on Do so existing project requiring Do may need to require Dox instead, unless it's using the Moo enhancements and type stuff and doesn't care about the standard library.

Additionally, I'm considering moving the Function:: Parameters work out into it's own pragma, e.g.

- typeable

```perl
use strict;
use warnings;
use typeable;

# do something
```

This will allow other scripts and modules that want a similar configuration to Do to be able to leverage that without requiring the core or stdlib.

## Community Project

I'd like to make Do a community project and create an organization to run and manage it. If you agree, what should we call the organization? Here's some ideas off the top of my head, e.g.

- doxers
- doers
- usedo
- modern-perl

**Comment by iamalnewkirk** [comment]
Please share your thoughts:

@srchulo
@brummett
@jjatria

**Comment by srchulo** [comment]
I like the idea of separating the two, and I do think that would lead to more stability. But just to make sure that I understand, the pluggable standard library is all of the Autobox Funcs?

Dox = Do extend?

For the Function::Parameters pragma, is that to reuse the exact same settings that we configure for Function::Parameters? I think that is a good idea, but it's not clear to me why it would be called typeable?

I think an organization to run and manage it is a good idea. I feel as though modern-perl is probably too general without something else with it, like dox-modern-perl. Without that, some may confuse it with the [module](https://metacpan.org/pod/Modern::Perl) or the [book](http://modernperlbooks.com/books/modern_perl_2016/), and it would probably make Googling harder for both.

I think do-modern-perl is good because of the play on words, but I wonder if it's still too close to Modern::Perl? If it is, perl-doers may be a good name. Or modern-perl-doers, but then that's Modern Perl again :)

**Comment by iamalnewkirk** [comment]
@srchulo:

- Yes, the pluggable standard library is all of the Functors (autobox, etc).
- Yes, Dox is a kind of initialism for Data-Object Extension
- Yes, the typeable? pragma is to reuse the same Function::Parameters settings 

There's already _"signatures_" and _"methods"_ pragmas, so I thought I might use _"routines"_ or _"typeable"_. Maybe _"routines"_ is the better fit!

With regards to the community initiative, on second thought, maybe we should join and donate the project to the Moose community at https://github.com/moose? If you agree, I'll start the conversation and see if that's something that interests them!

**Comment by iamalnewkirk** [comment]
Todo:

- [ ] Reduce: Do
- [ ] Publish: Dox
- [ ] Pragma: routines

**Comment by iamalnewkirk** [comment]
Published pragma, http://metacpan.org/release/routines

**Comment by iamalnewkirk** [comment]
This project has been deprecated in favor of https://metacpan.org/release/Data-Object and other separate releases!
